### ISSUE TITLE
Review and revise all SEPTA entries

### ISSUE THREAD

**Issue by rcheetham** [opendataphilly/opendataphilly-jkan#66]
There are 14 catalog entries for SEPTA but many of the resources have been moved. In addition, SEPTA has released new data sets that are not listed. We need to take several actions:

 - [x] Review existing SEPTA entries for accuracy and availability
 - [x] Review new SEPTA open data resources and add or consolidate where appropriate:
   - [x] GIS data portal on Esri - https://gis-septa.hub.arcgis.com/
   - [x] Ridership dashboard - https://data.septa.org/
   - [x] Developer API portal - https://www3.septa.org/

The datasets need to be reorganized into the following entries:
 - [x] SEPTA Real-time APIs
 - [x] SEPTA Real-time Map
 - [x] SEPTA Route and Stop Locations
 - [x] SEPTA GTFS
 - [x] SEPTA GTFS-RT alerts and updates
 - [x] SEPTA Ridership statistics
 - [x] SEPTA Dashboards
 - [x] SEPTA Finance
 - [x] SEPTA Trip Planner - plan.septa.org
 - [x] SEPTA SMS
 - [x] SEPTA Schedules
 - [x] move SEPTA train lateness to Phor and update

**Comment by arigas2** [comment]
https://www5.septa.org/bulletins/septa-invites-the-public-to-view-and-test-new-beta-website/

I'm not sure how this will affect ODP SEPTA catalog entries, but SEPTA has a new beta website and plans to migrate soon. Curious what others think, but perhaps it's better to wait until this happens to tackle this issue.

**Comment by rcheetham** [comment]
From browsing the new SEPTA beta site, I don't see evidence that this new version will result in new URLs or content for the API endpoints, GIS data portal (which is externally hosted by Esri), or ridership dashboard, and I don't think the risk of fixing the currently bad data is very high.

**Comment by arigas2** [comment]
Here are some notes after looking over existing entries and new SEPTA resources:

1. existing entries notes: https://docs.google.com/document/d/13IBBk3idnH4iksOvhW4bEk7VoSFRYFofmm13-fYHbyI/edit

2. new API developer portal - this documents each of the API endpoints that already exist in OpenDataPhilly, giving more accurate and detailed information about each endpoint than exists in OpenDataPhilly.

3. Additional new resources:

           -  There is an open data portal (https://planning.septa.org/open-data-portal/), that can filter by ridership, finance, and GIS data. Additionally it links to the ridership dashboard shared above in the initial comment.
           - There is this portal specifically to GIS data (https://gis-septa.hub.arcgis.com/), also shared above in initial comment. This same data can be accessed from open data portal above.

These new resources seem to be an upgrade over existing entries. My initial idea is: to have one entry for developer portal and one entry for open data portal (unless there is reason to have entries for each of the components in these larger resources). These would replace most if not all of the existing entries for SEPTA, perhaps entries from external sources (Skookul, link to mobile site, etc.).

Since I'm still relatively unfamiliar with this data, any feedback on this would be great.
